# Generated by Django 4.1.2 on 2022-12-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_finalized_end_alter_finalized_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalized',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='finalized',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
