# Generated by Django 4.1.2 on 2022-11-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(default='monday', max_length=150),
            preserve_default=False,
        ),
    ]
