# Generated by Django 4.1.2 on 2022-11-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('day', models.CharField(max_length=150)),
            ],
        ),
    ]
