# Generated by Django 4.1.2 on 2022-12-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_finalized_end_alter_finalized_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalized',
            old_name='title',
            new_name='text',
        ),
    ]
